blank_issues_enabled: true
contact_links:
  - name: Project Discord / Community
    url: https://github.com/ranjithrajv/awesome-volunteer-computing/discussions
    about: For questions, discussions, or ideas, use GitHub Discussions
