name: Check Links

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0' # every Sunday at midnight

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose --no-progress ./**/*.md
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
This is an initiative to collect and curate Awesome List of volunteer computing projects to help foster a community-driven AI ecosystem.

With recent news like Micron discontinuing consumer RAM and (rumored)Samsung halting SATA SSD production, the demand for accessible compute power is only growing.
This list is a resource for anyone interested in this space. If you know of any projects, platforms, or tools that are missing, please contribute!